"""
Email service for sending completion reports.
Uses a thread pool executor for non-blocking SMTP operations.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from concurrent.futures import ThreadPoolExecutor
from typing import Dict, List, Any, Optional
from datetime import datetime
from collections import Counter

from jinja2 import Environment, FileSystemLoader

from config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_FROM_EMAIL

# Thread pool for non-blocking email sends
_executor = ThreadPoolExecutor(max_workers=2)

# Jinja2 environment for email templates
_template_dir = os.path.join(os.path.dirname(__file__), "templates")
_jinja_env = Environment(loader=FileSystemLoader(_template_dir))


def send_completion_report(to_email: str, report_data: Dict[str, Any]) -> None:
    """
    Send a completion report email asynchronously.

    Args:
        to_email: Recipient email address
        report_data: Full report data from gather_scrape_job_stats()
    """
    _executor.submit(_send_email_sync, to_email, report_data)


def _send_email_sync(to_email: str, report_data: Dict[str, Any]) -> bool:
    """
    Synchronous email sending via SMTP.

    Returns:
        True if email sent successfully, False otherwise
    """
    if not SMTP_USER or not SMTP_PASSWORD:
        print(f"[Email] SMTP credentials not configured, skipping email to {to_email}")
        return False

    try:
        # Render HTML template
        template = _jinja_env.get_template("email_report.html")
        html_content = template.render(**report_data)

        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Nurliya Report: {report_data['query']}"
        msg["From"] = SMTP_FROM_EMAIL or SMTP_USER
        msg["To"] = to_email

        # Plain text fallback
        plain_text = _generate_plain_text(report_data)
        msg.attach(MIMEText(plain_text, "plain", "utf-8"))
        msg.attach(MIMEText(html_content, "html", "utf-8"))

        # Send via SMTP
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(msg["From"], [to_email], msg.as_string())

        print(f"[Email] Sent completion report to {to_email} for query: {report_data['query']}")
        return True

    except Exception as e:
        print(f"[Email] Failed to send email to {to_email}: {e}")
        return False


def _generate_plain_text(data: Dict[str, Any]) -> str:
    """Generate plain text version of the report."""
    lines = [
        "NURLIYA SENTIMENT ANALYSIS REPORT",
        "=" * 40,
        "",
        f"Query: {data['query']}",
        f"Generated: {data['generated_at']}",
        "",
        "EXECUTIVE SUMMARY",
        "-" * 20,
        f"Total Reviews: {data['total_reviews']}",
        f"Positive: {data['overall_positive']} ({data['overall_positive_pct']}%)",
        f"Neutral: {data['overall_neutral']} ({data['overall_neutral_pct']}%)",
        f"Negative: {data['overall_negative']} ({data['overall_negative_pct']}%)",
    ]

    if data['total_urgent'] > 0:
        lines.append(f"URGENT ISSUES: {data['total_urgent']}")

    for place in data['places_stats']:
        lines.extend([
            "",
            "-" * 40,
            f"PLACE: {place['name']}",
            f"Category: {place.get('category', 'N/A')}",
            f"Google Rating: {place.get('google_rating', 'N/A')}",
            "",
            f"Sentiment: +{place['sentiment']['positive']} / ~{place['sentiment']['neutral']} / -{place['sentiment']['negative']}",
        ])

        if place.get('top_positive'):
            topics = [f"{t['name']} ({t['count']})" for t in place['top_positive'][:3]]
            lines.append(f"What customers love: {', '.join(topics)}")

        if place.get('positive_summaries'):
            lines.append("Positive feedback:")
            for s in place['positive_summaries'][:2]:
                lines.append(f'  "{s}"')

        if place.get('top_negative'):
            topics = [f"{t['name']} ({t['count']})" for t in place['top_negative'][:3]]
            lines.append(f"Areas to improve: {', '.join(topics)}")

        if place.get('negative_summaries'):
            lines.append("Negative feedback:")
            for s in place['negative_summaries'][:2]:
                lines.append(f'  "{s}"')

        if place.get('urgent_count', 0) > 0:
            lines.append(f"URGENT: {place['urgent_count']} reviews need attention")

    if data.get('actions'):
        lines.extend(["", "RECOMMENDED ACTIONS", "-" * 20])
        for i, action in enumerate(data['actions'][:3], 1):
            lines.append(f"{i}. {action}")

    lines.extend([
        "",
        "-" * 40,
        "Generated by Nurliya - AI-powered review analysis",
    ])

    return "\n".join(lines)


def _generate_actions(places_stats: List[Dict], total_urgent: int) -> List[str]:
    """Generate recommended actions based on the analysis."""
    actions = []

    # Check for urgent issues
    if total_urgent > 0:
        actions.append(f"Address {total_urgent} urgent review(s) immediately - these indicate serious customer concerns that need quick resolution.")

    # Aggregate all negative topics
    all_negative_topics = Counter()
    all_positive_topics = Counter()
    for place in places_stats:
        for topic in place.get('top_negative', []):
            all_negative_topics[topic['name']] += topic['count']
        for topic in place.get('top_positive', []):
            all_positive_topics[topic['name']] += topic['count']

    # Top negative topic action
    if all_negative_topics:
        top_neg = all_negative_topics.most_common(1)[0]
        actions.append(f"Focus on improving '{top_neg[0]}' - mentioned negatively in {top_neg[1]} review(s).")

    # Leverage positive
    if all_positive_topics:
        top_pos = all_positive_topics.most_common(1)[0]
        actions.append(f"Continue excelling at '{top_pos[0]}' - customers love this! Consider highlighting it in marketing.")

    # Check sentiment balance
    for place in places_stats:
        total = sum(place['sentiment'].values())
        if total > 0:
            neg_pct = place['sentiment']['negative'] / total * 100
            if neg_pct > 30:
                actions.append(f"'{place['name']}' has {neg_pct:.0f}% negative reviews - consider a service quality review.")
                break

    return actions[:3]


def gather_scrape_job_stats(scrape_job_id: str) -> Optional[Dict[str, Any]]:
    """
    Gather comprehensive statistics for all places in a scrape job.

    Returns:
        Dict with all data needed for email template
    """
    from database import ScrapeJob, Job, Place, Review, ReviewAnalysis, get_session

    session = get_session()
    try:
        scrape_job = session.query(ScrapeJob).filter_by(id=scrape_job_id).first()
        if not scrape_job:
            return None

        places_stats = []
        overall_positive = 0
        overall_neutral = 0
        overall_negative = 0
        total_urgent = 0

        if scrape_job.pipeline_job_ids:
            for job_id in scrape_job.pipeline_job_ids:
                job = session.query(Job).filter_by(id=job_id).first()
                if not job or not job.place_id:
                    continue

                place = session.query(Place).filter_by(id=job.place_id).first()
                if not place:
                    continue

                # Get all analyses with their reviews for this place
                results = (
                    session.query(ReviewAnalysis, Review)
                    .join(Review, Review.id == ReviewAnalysis.review_id)
                    .filter(Review.place_id == place.id)
                    .all()
                )

                # Calculate stats
                sentiment_counts = {"positive": 0, "neutral": 0, "negative": 0}
                urgent_count = 0
                positive_topics = Counter()
                negative_topics = Counter()
                positive_summaries = []
                negative_summaries = []
                urgent_summaries = []

                for analysis, review in results:
                    # Count sentiments
                    if analysis.sentiment in sentiment_counts:
                        sentiment_counts[analysis.sentiment] += 1

                    # Collect topics
                    for topic in analysis.topics_positive or []:
                        positive_topics[topic] += 1
                    for topic in analysis.topics_negative or []:
                        negative_topics[topic] += 1

                    # Collect summaries (prefer English, fallback to Arabic)
                    summary = analysis.summary_en or analysis.summary_ar
                    if summary:
                        if analysis.urgent:
                            urgent_count += 1
                            urgent_summaries.append(summary)
                        elif analysis.sentiment == "positive":
                            positive_summaries.append(summary)
                        elif analysis.sentiment == "negative":
                            negative_summaries.append(summary)

                # Update totals
                overall_positive += sentiment_counts["positive"]
                overall_neutral += sentiment_counts["neutral"]
                overall_negative += sentiment_counts["negative"]
                total_urgent += urgent_count

                # Format topics as list of dicts with name and count
                top_positive = [{"name": t, "count": c} for t, c in positive_topics.most_common(5)]
                top_negative = [{"name": t, "count": c} for t, c in negative_topics.most_common(5)]

                place_stat = {
                    "name": place.name,
                    "place_id": str(place.id),
                    "category": place.category,
                    "address": place.address,
                    "google_rating": float(place.rating) if place.rating else None,
                    "google_review_count": place.review_count,
                    "total_reviews": len(results),
                    "sentiment": sentiment_counts,
                    "urgent_count": urgent_count,
                    "top_positive": top_positive,
                    "top_negative": top_negative,
                    "positive_summaries": positive_summaries[:3],
                    "negative_summaries": negative_summaries[:3],
                    "urgent_summaries": urgent_summaries[:3],
                }

                places_stats.append(place_stat)

        # Calculate overall percentages
        total_reviews = overall_positive + overall_neutral + overall_negative
        if total_reviews > 0:
            overall_positive_pct = round(overall_positive / total_reviews * 100)
            overall_neutral_pct = round(overall_neutral / total_reviews * 100)
            overall_negative_pct = round(overall_negative / total_reviews * 100)
        else:
            overall_positive_pct = overall_neutral_pct = overall_negative_pct = 0

        # Generate action items
        actions = _generate_actions(places_stats, total_urgent)

        return {
            "query": scrape_job.query,
            "scrape_job_id": str(scrape_job.id),
            "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            "places_stats": places_stats,
            "total_reviews": total_reviews,
            "total_urgent": total_urgent,
            "overall_positive": overall_positive,
            "overall_neutral": overall_neutral,
            "overall_negative": overall_negative,
            "overall_positive_pct": overall_positive_pct,
            "overall_neutral_pct": overall_neutral_pct,
            "overall_negative_pct": overall_negative_pct,
            "actions": actions,
        }

    finally:
        session.close()
